# Cross.toml for ARM64 cross-compilation with stable container
[build.env]
passthrough = [
    "GITHUB_ACTIONS",
    "GITHUB_ACTOR", 
    "GITHUB_RUN_ID"
]

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
