[build.env]
passthrough = [
    "RUST_LOG",
    "CROSS_CONTAINER_IN_CONTAINER",
]

# Let Cross use its default images for better compatibility
[target.aarch64-unknown-linux-gnu]

[target.aarch64-unknown-linux-musl]
